# Generated by Django 4.2.16 on 2024-12-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamtv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=1, default='NULL', max_digits=3, null=True),
        ),
    ]
