# Generated by Django 4.2.16 on 2024-12-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamtv', '0002_alter_episode_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='founding_date',
        ),
    ]
