# Generated by Django 4.2.16 on 2025-01-08 12:25

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamtv', '0003_remove_artist_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['serie', 'season_num', 'number']},
        ),
        migrations.AlterField(
            model_name='episode',
            name='airing_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1900, 1, 1))]),
        ),
        migrations.AlterField(
            model_name='episode',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ep_directed', to='streamtv.artist'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='streamtv.serie'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ep_produced', to='streamtv.studio'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='creation_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 1, 8))]),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='saved_episodes',
            field=models.ManyToManyField(related_name='in_playlists', to='streamtv.episode'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_playlists', to='streamtv.registered_user'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='birth_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 1, 8))]),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='fav_series',
            field=models.ManyToManyField(related_name='favorite_of', through='streamtv.UserFavoriteSerie', to='streamtv.serie'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='followed_artists',
            field=models.ManyToManyField(blank=True, related_name='followers', to='streamtv.artist'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='followed_studios',
            field=models.ManyToManyField(blank=True, related_name='followers', to='streamtv.studio'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='reviews',
            field=models.ManyToManyField(related_name='reviewed_by', through='streamtv.UserReview', to='streamtv.episode'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='watch_history',
            field=models.ManyToManyField(related_name='watched_by', through='streamtv.UserWatchHistory', to='streamtv.episode'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='streamtv.franchise'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_studio', to='streamtv.artist', unique=True),
        ),
        migrations.AlterField(
            model_name='userfavoriteserie',
            name='added_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 1, 8))]),
        ),
        migrations.AlterField(
            model_name='userfavoriteserie',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_favorite', to='streamtv.serie'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='streamtv.episode'),
        ),
        migrations.AlterField(
            model_name='userwatchhistory',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to='streamtv.episode'),
        ),
        migrations.AlterField(
            model_name='userwatchhistory',
            name='watch_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 1, 8))]),
        ),
    ]
