# Generated by Django 4.2.16 on 2025-01-09 14:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamtv', '0004_alter_episode_options_alter_episode_airing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='airing_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='creation_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 1, 9))]),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userfavoriteserie',
            name='added_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 1, 9))]),
        ),
        migrations.AlterField(
            model_name='userwatchhistory',
            name='watch_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 1, 9))]),
        ),
    ]
