# Generated by Django 4.2.16 on 2025-01-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamtv', '0005_alter_episode_airing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwatchhistory',
            name='watch_date',
            field=models.DateField(),
        ),
    ]
