# Generated by Django 4.2.16 on 2025-01-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamtv', '0006_alter_userwatchhistory_watch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userfavoriteserie',
            name='added_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='vote',
            field=models.CharField(choices=[('Positive', 'Positive vote'), ('Negative', 'Negative vote')], max_length=8),
        ),
    ]
