# Generated by Django 4.2.16 on 2025-01-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamtv', '0007_alter_playlist_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered_user',
            old_name='birth_date',
            new_name='registration_date',
        ),
    ]
