# Generated by Django 4.2.16 on 2025-01-11 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamtv', '0008_rename_birth_date_registered_user_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user',
            name='birth_date',
            field=models.DateField(default=datetime.date(1901, 1, 1)),
            preserve_default=False,
        ),
    ]
