# Generated by Django 4.2.16 on 2025-02-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamtv', '0009_registered_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='studio_head',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_studio', to='streamtv.artist', unique=True),
            preserve_default=False,
        ),
    ]
